### ISSUE TITLE
Recurrent Neural Networks

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/DS-ScriptsNook#100]
Hey DCP participants, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Introduction to Recurrent Neural Networks. Tutorial to Recurrent Neural Networks and how it's applied using sample code.

"Project Title" should be the "Issue Title" mentioned here.

If you like to work on this issue, follow the given guidelines for code as well as for the README. You have to be as elaborative as possible. Make sure you also maintain the project structure provided. Just comment and get it assigned. Issues are alloted on FCFS basis.

The main intention of this repo is to educate beginners with all the concepts related to datascience so that they could feel confident to apply these things learnt in practical exposure.

Enjoy your open source journey ahead. 😎

**Comment by avinash-218** [comment]
Define You:

- [x] Hacktoberfest2021 Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
- I would like to contribute <b>Recurrent Neural Network using Google stock price dataset.

**Describe the solution you'd like...**

Steps:
- Import Dataset and Libraries
- Feature Scaling
- Building Architecture of the Neural Network
- Compiler the network
- FIt the network
- Predict and visualize the result
- Evaluate the model

**Comment by prathimacode-hub** [comment]
Issue assigned to @avinash-218

**Comment by tanvideshmukh29** [comment]
@prathimacode-hub
I would love to contribute mam as a part of hacktoberfest2021.
Can you assign this to me?
