### ISSUE TITLE
Live Barcode and QR Code Reader

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/DS-ScriptsNook#107]
Hey DCP participants, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Live Barcode & QR Code Reader. Tutorial to Live Barcode & QR Code Reader and how it's applied using sample code.

Topic : Computer Vision

"Project Title" should be the "Issue Title" mentioned here.

If you like to work on this issue, follow the given guidelines for code as well as for the README. You have to be as elaborative as possible. Make sure you also maintain the project structure provided. Just comment and get it assigned. Issues are alloted on FCFS basis.

The main intention of this repo is to educate beginners with all the concepts related to datascience so that they could feel confident to apply these things learnt in practical exposure.

Enjoy your open source journey ahead. 😎

**Comment by hrugved06** [comment]
Define You:

- [x] DevIncept Participant 
- [x] Contributor


**Is your feature request related to a problem? Please describe.**

I would like to add a tutorial on the creation of a Live Barcode and QR Code Reader that is trained in the local environment, this will be a real-time QR/Barcode Scanner which will be a .py file, where I will be explaining each and every step. I will also add a .ipynb file if needed.

**Describe the solution you'd like...**

Steps which will be following:-
<ol>
  <li>Setting up a local enviornment</li>
  <li>Importing the packages through the command line</li>
  <li>Setting-up the required dependencies</li>
  <li>Creating main function to run the model</li>
  <li>Adding suitable variables and parameters</li>
  <li>Then Finally, Testing </li>

</ol>

**Dataset to be used:-** No dataset required (Real-time detection)

@prathimacode-hub please do assign the issue :-D

**Comment by prathimacode-hub** [comment]
Issue assigned. @hrugved06
