### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by payaldutta** [prathimacode-hub/DS-ScriptsNook#11]
**Description**

Create Contributors Guideline to help new Contributors get started with this Project.

**Additional Details**

*Add a CONTRIBUTING.md to allow new users to get started with knowing how to contribute.
*Add Screenshots wherever possible.
*Add the basic information about creating Issues, Pull Requests and Branching.
*Mention tutorials related to Git and Github to help them better understand.

**Comment by prathimacode-hub** [comment]
Why did you close the issue? @payaldutta

**Comment by prathimacode-hub** [comment]
You should never close issue or PR from your end. @payaldutta
