### ISSUE TITLE
Data Preprocessing in ML

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/DS-ScriptsNook#110]
Hey DCP participants, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Data Preprocessing . Tutorial to Data Preprocessing  and how it's applied using sample code.

"Project Title" should be the "Issue Title" mentioned here.

If you like to work on this issue, follow the given guidelines for code as well as for the README. You have to be as elaborative as possible. Make sure you also maintain the project structure provided. Just comment and get it assigned. Issues are alloted on FCFS basis.

The main intention of this repo is to educate beginners with all the concepts related to datascience so that they could feel confident to apply these things learnt in practical exposure.

Enjoy your open source journey ahead. 😎

**Comment by dilroseR** [comment]
can i do this?

**Comment by prathimacode-hub** [comment]
Yes, you can proceed. Issue assigned. @dilroseR

**Comment by dilroseR** [comment]
may i know how many points are for this issue?

**Comment by prathimacode-hub** [comment]
> may i know how many points are for this issue?

Points can be judged only once PR is done. Based on the work showcased. @dilroseR

**Comment by prathimacode-hub** [comment]
Update please? @dilroseR

**Comment by dilroseR** [comment]
will make a pr today or tommorrow
