### ISSUE TITLE
Social Distance Detection 

### ISSUE THREAD

**Issue by anubhav201241** [prathimacode-hub/DS-ScriptsNook#116]
---
Title: Social Distance Detector
About: Give alerts and warn the people when they come near to each other, Detect the live camera feed  
Name: Anubhav
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, it is as it comes under the DS-ScriptsNook it's detect the people whether they are maintaining social distancing or not with the help of Computer Vision and Open Cv

**Describe the solution you'd like...**

Want to contribute to the repository.

**Describe alternatives you've considered?**

Implement it Deep learning algorithm 

**Additional context**

@prathimacode-hub Kindly assign this issue to me :)

**Comment by prathimacode-hub** [comment]
Kindly follow the guidelines given. Creat an issue template with project details. And also go through the README file of the project for overview of project structure. @anubhav201241

**Comment by anubhav201241** [comment]
@prathimacode-hub Can I contribute to it I have made the issue template for it :)

**Comment by prathimacode-hub** [comment]
Yes. But last date to merge up the PR's is tomorrow. Only if you could assure that PR will be submitted by tomorrow I can assign it to you. @anubhav201241

**Comment by anubhav201241** [comment]
Sure I will :) made the Pr by today itself

**Comment by prathimacode-hub** [comment]
Cool, issue assigned. @anubhav201241

**Comment by prathimacode-hub** [comment]
I didn't expect this from you. Being a participant of open source program, I thought you would atleast do the changes for the  time exception I had given to you. I asked time for you from the team. All you do is close up the PR without no response. @anubhav201241

**Comment by anubhav201241** [comment]
I have done the changes but still you are kept asking me do that change I have tried it I have created proper issue and pull request template work on coding part and made the PR but still you are asking me to do more changes I have simply said to you that I have created my pr you can merge it if you want and then you can add that folder in that specific folder in which you want to add but still no problem
