### ISSUE TITLE
Random Forest Regressor Algorithm.

### ISSUE THREAD

**Issue by ayushi424** [prathimacode-hub/DS-ScriptsNook#13]
Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

- I want to contribute **Random Forest Regressor Algorithm** using this [dataset](https://www.kaggle.com/ionaskel/laptop-prices) by following the given project structure.

**Describe the solution you'd like...**

-  I'll proceed by following steps:
Step 1: Data preprocessing and exploration.
Step 2: Data visualization to draw useful insights.
Step 3: Data training & model creation using random forest regressor algorithm.
Step 4: Check efficiency of this algorithm by error & accuracy check.

@prathimacode-hub, please assign it to me.

**Comment by prathimacode-hub** [comment]
Issue assigned. @ayushi424
