### ISSUE TITLE
NLP based Chatbot

### ISSUE THREAD

**Issue by hrugved06** [prathimacode-hub/DS-ScriptsNook#14]
Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

I would like to add a tutorial on the creation of an NLP based Chatbot that is trained with Microsoft's DialoGPT model in Google Colab using its free GPU, which will be a .ipynb file, where I will be explaining each and every step.

**Describe the solution you'd like...**

Steps which will be following:-
<ol>
  <li>Drive Mounting and locating the dataset</li>
  <li>Importing required Packages and transformers</li>
  <li>Setting-up the variables</li>
  <li>Preparation of the dataset</li>
  <li>Training and Evaluatuing the model</li>
  <li>Then Finally, Testing </li>

</ol>

**Dataset to be used :-** <a href="https://www.kaggle.com/andradaolteanu/rickmorty-scripts">Dataset</a>

**Datasets can be used (optional):-** Alternatives For the Dataset:- 1.<a href="https://www.kaggle.com/anderfj/game-of-thrones-series-scripts-breakdowns">GOT Script</a>  2.<a href="https://www.kaggle.com/mitramir5/the-big-bang-theory-series-transcript">Big Bang Theory Script</a>

**Comment by prathimacode-hub** [comment]
That's awesome. Are you an devincept participant? @hrugved06

**Comment by prathimacode-hub** [comment]
Issue assigned. @hrugved06

**Comment by prathimacode-hub** [comment]
Issue assigned. @hrugved06
