### ISSUE TITLE
K Medoid Based Clustering

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/DS-ScriptsNook#147]
Hey hacktoberfest participants, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about K Medoid Based Clustering. Tutorial to K Medoid Based Clustering and how it's applied using sample code.

"Project Title" should be the "Issue Title" mentioned here.

If you like to work on this issue, follow the given guidelines for code as well as for the README. You have to be as elaborative as possible. Make sure you also maintain the project structure provided. Just comment and get it assigned. Issues are allotted on FCFS basis.

The main intention of this repo is to educate beginners with all the concepts related to data science so that they could feel confident to apply these things learnt in practical exposure.

Enjoy your open source journey ahead. 😎

**Comment by photon149** [comment]
Hello , I would like to work on the issue , will explain k medoid algorithm , alongside a proper neat impementation of the code plus a comparison of how the kmedoid algorithm performs in comparison to other algorithms as well.

**Comment by prathimacode-hub** [comment]
Issue assigned. @photon149
