### ISSUE TITLE
Decision Tree Classifier Algorithm.

### ISSUE THREAD

**Issue by ayushi424** [prathimacode-hub/DS-ScriptsNook#21]
Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

- I want to contribute **Decision Tree Classifier Algorithm** using this [dataset](https://www.kaggle.com/iabhishekofficial/mobile-price-classification?select=train.csv) by following the given project structure.

**Describe the solution you'd like...**

-  I'll proceed by following steps:
Step 1: Data preprocessing and exploration.
Step 2: Data visualization to draw useful insights.
Step 3: Data training & model creation using decision tree classifier algorithm.
Step 4: Performance evaluation to check efficiency of this algorithm by error & accuracy check.

@prathimacode-hub, please assign it to me.

**Comment by prathimacode-hub** [comment]
Issue assigned. @ayushi424
