### ISSUE TITLE
Word Tokenization Techniques in NLP

### ISSUE THREAD

**Issue by shivani6320** [prathimacode-hub/DS-ScriptsNook#22]
### Label: Feature Request

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
My feature requests to add an algorithm in NLP subject.
What is tokenization?
Tokenization is the process of breaking text into smaller pieces called tokens. These smaller pieces can be sentences, words, or sub-words. For example, the sentence “I won” can be tokenized into two word-tokens “I” and “won”.

**Describe the solution you'd like...**

I would describe different word tokenization techniques  like  Whitespace tokenization,Punctuation-based tokenization,Default/TreebankWordTokenizer,TweetTokenizer etc.. and practical implementation of it.

**Comment by prathimacode-hub** [comment]
Issue assigned. @shivani6320
