### ISSUE TITLE
YouTube Comments Classifier

### ISSUE THREAD

**Issue by hrugved06** [prathimacode-hub/DS-ScriptsNook#23]
Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

I would like to add a tutorial on the creation of a Youtube Comments Classifier model that classifies whether the comment is harmful or not and also disables the spammed links, and this will be a .ipynb file, where I will be explaining each and every step.

**Describe the solution you'd like...**

Steps which will be following:-
<ol>
  <li>Drive Mounting and locating the dataset</li>
  <li>Importing required Packages</li>
  <li>Preparation of the dataset (Arrangement and Cleaning)</li>
  <li>Setting up the variables</li>
  <li>Training and Evaluatuing the model</li>
  <li>Then Finally, Testing </li>

</ol>

**Dataset to be used :-** <a href="https://www.kaggle.com/prashant111/youtube-spam-collection">Dataset</a>

**Datasets can be used (optional):-** Alternatives For the Dataset:- <a href="https://www.kaggle.com/datasets?search=youtube+spam+comments">Optional Datasets</a>

Hey @prathimacode-hub, I would love to work on this problem statement. Do assign me the issue.
Thank You :-D

**Comment by prathimacode-hub** [comment]
Issue assigned. @hrugved06
