### ISSUE TITLE
Color identification using OpenCV

### ISSUE THREAD

**Issue by vishvarana** [prathimacode-hub/DS-ScriptsNook#27]
Script Title : Color identification in images
Suggest an script for this project : Python
YourName : Vishva Rana

✅ DevIncept Participant
 ✅Contributor
Is your feature request related to a problem? Please describe.
Problem is same as mentioned in title

Describe the solution you'd like...
This will detect color in images and show a pie chart of what different colours are used, also when given colour, it will bring out images that has the given colour

Please assign it to me under DCP'21

**Comment by prathimacode-hub** [comment]
Issue assigned. @vishvarana

**Comment by vishvarana** [comment]
PR made 
#30 
Please review and let me know if any changes required
