### ISSUE TITLE
Pandas-Series Notes

### ISSUE THREAD

**Issue by suy1968** [prathimacode-hub/DS-ScriptsNook#32]
Pandas-Series  Notes .

**Comment by suy1968** [comment]
please assign me as I am a contributor in DEVINCEPT @prathimacode-hub

**Comment by prathimacode-hub** [comment]
First go through the README and CONTRIBUTING GUIDELINES. Follow the issue template given to create an issue along with details of project and appropriate things to get it assigned. And you can work on only 1 topic at a time. Choose a single topic to work and change the issue title accordingly. You can change all the details using edit options. Never close issues or PR from your end. @suy1968

**Comment by prathimacode-hub** [comment]
I shall do one thing, I shall create issues now, give 20mins time. Once i create good number of issues, you can choose it from them. @suy1968

**Comment by suy1968** [comment]
Okay

**Comment by prathimacode-hub** [comment]
I started creating issues, do comment on them if anything interests you. @suy1968

**Comment by suy1968** [comment]
Okay Mam
