### ISSUE TITLE
Text Preprocessing in NLP

### ISSUE THREAD

**Issue by letus21500** [prathimacode-hub/DS-ScriptsNook#4]
I want to contribute to this project under DCP'21
I want to add the Text preprocessing or cleaning scripts in NLP. Eg. Lowercasing, Punctuation Removal, Removing stopwords, text standardization, Spelling correction, Tokenization, etc.

@prathimacode-hub Please assign this issue to me

**Comment by prathimacode-hub** [comment]
That's amazing. Welcome to DCP'21. Contributions would start from 10th of July. Raise up an an issue separately for each issue you would work on and get it assigned. Issues are purely assigned on First Come First Basis. So stay alerted and participant can work on only 1 issue at a time. This is to be fair with everyone. Any queries, don't hesitate to ask. All the best for your open source journey. @letus21500

**Comment by prathimacode-hub** [comment]
If you to interested to work on this issue, kindly create a new issue with the title using issue template provided. @letus21500

**Comment by letus21500** [comment]
I am really really sorry! But I was got too busy to do this! Really sory for doing this.

**Comment by prathimacode-hub** [comment]
ok
