### ISSUE TITLE
Adding ML algorithm- Linear Regression

### ISSUE THREAD

**Issue by ayushi424** [prathimacode-hub/DS-ScriptsNook#5]
Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
I want to contribute a Machine Learning Algorithm i.e. Linear Regression, which is the most simple and basic ml algorithm.

**Describe the solution you'd like...**

I would follow steps:
- Step 1  Data Preprocessing and exploration.
- Step 2 Data Cleaning(This is an optional step, if there are any missing or null values in the data, replace or remove them)
- Step 3 Model Creation using linear regression algorithm.
- Step 4 Lastly a  performance check using accuracy & error check to find how efficient algorithm is.
 
**Dataset to used:** 
[Dataset](https://www.kaggle.com/quantbruce/real-estate-price-prediction)

**Comment by prathimacode-hub** [comment]
Sure, issue assigned. Welcome back to this new repo as a DevIncept participant. Kindly go through the project structure given before you work on issue. All the best. @ayushi424
