### ISSUE TITLE
Random Forest Classifier 

### ISSUE THREAD

**Issue by vaishnavipatil4848** [prathimacode-hub/DS-ScriptsNook#6]
Define You:

DevIncept Participant

**Is your feature request related to a problem? Please describe.**
I want to contribute Machine Learning Algorithm-Random Forest Classifier explaining the logic as well as practical implementation.

Describe the solution you'd like...

**Steps to be followed:**

* Explanation of the Working of Random Forest Classifier Algorithm.
*  Exploring the data and visualization(if needed).
*  Model creation and Inference.
*  Lastly measuring the efficiency of  model using particular model.

Dataset to used:
[Dataset](https://www.kaggle.com/balaka18/email-spam-classification-dataset-csv)

**Comment by prathimacode-hub** [comment]
Hey, hope you understood the intent of the project. Here specific projects are not accepted. But instead choose an algorithm you would like to work on. For example decision tree classifier, create this repository. Now explain decision tree classifier using project file and README taking some project like this into consideration. This means if you want to work on email spam classification, then in project file, read the dataset, do the analysis for this project and only use decision tree classifier to make prediction. Hope you understood, this repo is all about understanding and utilizing the concept effectively. It's like a learning journey. When you choose an algorithm, you should provide concerning that algorithm. For the very same, I had give the project structure in README file of the project and also README template is given as things that should be added in README file. So kindly change the issue title and template details accordingly and get this issue assigned. @vaishnavipatil4848

**Comment by vaishnavipatil4848** [comment]
Thank you for clarification.  The issue has been updated by me.

**Comment by prathimacode-hub** [comment]
> Thank you for clarification. The issue has been updated by me.

Cool, change the issue title as well to the "Algorithm Name". @vaishnavipatil4848

**Comment by prathimacode-hub** [comment]
I had assigned issue to you. You can proceed. @vaishnavipatil4848
