### ISSUE TITLE
Ridge Regression

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/DS-ScriptsNook#93]
Hey DCP participants, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Ridge Regression. Tutorial to Ridge Regression and how it's applied using sample code.

"Project Title" should be the "Issue Title" mentioned here.

If you like to work on this issue, follow the given guidelines for code as well as for the README. You have to be as elaborative as possible. Make sure you also maintain the project structure provided. Just comment and get it assigned. Issues are alloted on FCFS basis.

The main intention of this repo is to educate beginners with all the concepts related to datascience so that they could feel confident to apply these things learnt in practical exposure.

Enjoy your open source journey ahead. 😎

**Comment by ayushi424** [comment]
Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

- I want to contribute **Ridge Regression Algorithm** using this [dataset](https://www.kaggle.com/rohanrao/air-quality-data-in-india) by following the given project structure.

**Describe the solution you'd like...**

-  I'll proceed by following steps:
Step 1: Data preprocessing and exploration.
Step 2: Data visualization to draw useful insights.
Step 3: Data training & model creation.
Step 4: Performance evaluation to check efficiency of the algorithm by error & accuracy check.

@prathimacode-hub, please assign it to me.

**Comment by prathimacode-hub** [comment]
Issue assigned. But remember 9th is the last date to accept PR's. @ayushi424
